### PR TITLE
Support native docker backend

### PR DESCRIPTION
**Pull request by adepretis**
For local development with multiple application services we need traefik to integrate with docker as backend.

I added two new environment variables (``TRAEFIK_ENABLE_DOCKER`` and ``TRAEFIK_DOCKER_ENTRYPOINT``).

The only problem with the docker integration is, that the traefik process needs to access the socket (if ``TRAEFIK_DOCKER_ENTRYPOINT`` is a socket) and the container has to be started with user ``root``.

### CODE REVIEW

**Comment by adepretis** [comment]
any comment @rawmind0?

**Comment by claflico** [comment]
I think that I could benefit from this....We're moving away from Rancher Cattle but not quite to Kubernetes yet so experimenting with Portainer and standalone hosts for now....am trying to use the main traefik image but having difficulty getting the cert syntax correct.

**Comment by rawmind0** [comment]
Released image `rawmind0/alpine-traefik:1.7.12-1`

**Comment by claflico** [comment]
@adepretis @rawmind0 Just saw a typo. Readme says "TRAEFIK_DOCKER_ENTRYPOINT" but code says "TRAEFIK_DOCKER_ENDPOINT"

Also, should there have been TRAEFIK_DOCKER_DOMAIN & TRAEFIK_DOCKER_EXPOSED variables?

**Pull request merged**
