### PR TITLE
Update to traefik version 1.2.1

### PR DESCRIPTION
**Pull request by adepretis**

### CODE REVIEW

**Comment by adepretis** [comment]
any comments @rawmind0 ? ;-)

**Comment by rawmind0** [comment]
Just one....Thanks so much for the PR...  ;P

LGTM...

**Comment by adepretis** [comment]
no problem ;-) ... btw. could you please trigger a build for Dockerhub too? @rawmind0

**Comment by rawmind0** [comment]
Sure...Sory.. :P 
Done...

**Pull request merged**
