### PR TITLE
Enabled wildcard domain certification

### PR DESCRIPTION
**Pull request by dgautumn**
Add a variable to support wildcard domain.

### CODE REVIEW

**Comment by krumware** [comment]
@dgautumn any reason the PR was closed?  I think because it was taking a while for it to be merged?

**Comment by dgautumn** [comment]
I just check that was hold for a month ago and did not merged, so i closed it . Not for other reason. Thanks for your advisement.

**Comment by rawmind0** [comment]
I'm sorry about that @dgautumn . So busy last months and i couldn't attend your PR properly.

**Comment by krumware** [comment]
I'll update the other PR with some of that material and we can get this in there :thumbsup:

**Pull request closed without merging**
