### PR TITLE
Add TRAEFIK_FILE_ENABLE option (default: true)

### PR DESCRIPTION
**Pull request by adepretis**

### CODE REVIEW

**Comment by rawmind0** [comment]
Hi @adepretis ... Thanks for your PR... :)

LGTM...

**Comment by rawmind0** [comment]
Released in rawmind/alpine-traefik:1.4.0-4 

:)

**Comment by rawmind0** [comment]
Sorry guys, use rawmind/alpine-traefik:1.4.0-6 or new rawmind/alpine-traefik:1.4.1-2

**Comment by adepretis** [comment]
damn, sorry, totally overlooked the „-=„ instead of „==„ :-(

**Comment by rawmind0** [comment]
Don't worry... My fault reviewing... ;)

Solved in current versions..

**Pull request merged**
