### PR TITLE
ACME support

### PR DESCRIPTION
**Pull request by fabiorauber**
This enables the use of Let's Encrypt Certificates via ACME Protocol, already supported by Traefik. There is a corresponding PR for rancher-traefik.

### CODE REVIEW

**Comment by rawmind0** [comment]
Thanks @fabiorauber...good job!! :)

One little thing... I think that line 45 of root/opt/traefik/bin/traefik.toml.sh 
storageFile = \"/opt/tools/acme/acme.json\"

I think it's better to create the file inside ${SERVICE_HOME}/acme/acme.json, due to you are trying to safe the file in a cross location that it isn't mandatory. It wouldn't exist if you run alpine-traefik alone.

Could you please change that??

**Comment by fabiorauber** [comment]
Actually I tried that directory, but encountered several permission problems. Mainly because when you deploy inside rancher, you have to import volumes from rancher-traefik (volumes_from directive). If the folder does not exist inside rancher-traefik image, then the folder becomes owned by root, not by traefik user, and then Traefik stops working...

**Comment by rawmind0** [comment]
Traefik is running with traefik user. All files under /opt/traefik and /opt/tools are owned by him.  It has to be created in Dockerfile or in alpine-traefik, due to rancher-traefik is a sidekick. 

It hasn't to be a problem.....

**Comment by fabiorauber** [comment]
I thought so too, and created the folder with Dockerfile. But it failed every time with rancher-traefik as the source of the volumes. Since we are using volumes_from,  the acme volume had to be created on the sidekick, and ${SERVICE_HOME}/acme does not exist there.

**Comment by rawmind0** [comment]
From rancher-traefik only /opt/tools is mounted. I think the folder has to be created in alpine-traefik /opt/traefik/acme . ACME feature is a feature from alpine-traefik, not from rancher-traefik. 

alpine-traefik could be run alone, without rancher-traefik. Then it would be nice that if it's run alone it has ACME feature too...

rancher-traefik, feature is only to provide dynamic config from rancher to traefik....

Your rancher-traefik PR is perfect, but i think the file location here is not correct.

**Comment by fabiorauber** [comment]
I think that is the best location too, I just did not manage to make it work inside rancher at that folder. I'm just saying that if you mount it as a volume, and you should do that to preserve the certificates,  you will have to create in the rancher-traefik container. We can't create on the alpine-traefik container because of the volumes_from directive, and so we have a permission problem.

**Comment by rawmind0** [comment]
I don't understand your point that volumes_from is a problem to create acme folder in alpine-traefik. Ok i understand that you have permission problems, but avoiding them volumes_from is not a problem...

One question about my low knowledge about letsencrypt...Do you need to persist acme.json?? If you loose this file, you loose certs?? I thought that you could download your certs from letsencrypt, but reading your last comment, i'm thinking that i was wrong in that...

**Comment by fabiorauber** [comment]
I maybe doing It the wrong way, but I was in a dead end trying to make it work at ${SERVICE_HOME}/acme location as a volume, so /opt/tools was how I found it would work. 

About Let's Encrypt, every time you download a certificate, it is a new one, and they rate limit new certificates at 5 per domain or subdomain per 7 days. If you have lots of certificates, they might as well rate limit per IP Address, to protect their infrastructure. So it is recommended to persist the  file.

**Comment by rawmind0** [comment]
Thanks for the letsencrypt answer...I was wrong with that...I agree with you it's recommended to persist the file, but i don't know if racher-traefik is the best place....

How did you try to create the folder?? I'm gonna merge and try, ok??

Thanks so much @fabiorauber ... :D

**Comment by rawmind0** [comment]
@fabiorauber could you try the new release, please?? 

I've created folder in alpine-traefik /opt/traefik/acme owned by traefik user and its working ok... :D

8/17/2016 11:31:44 PMtime="2016-08-17T21:31:44Z" level=info msg="Traefik version v1.0.2 built on 2016-08-02_05:35:02PM" 
8/17/2016 11:31:44 PMtime="2016-08-17T21:31:44Z" level=info msg="Using TOML configuration file /opt/traefik/etc/traefik.toml" 
8/17/2016 11:31:44 PMtime="2016-08-17T21:31:44Z" level=info msg="Preparing server http &{Network: Address::8080 TLS:<nil> Redirect:<nil>}" 
8/17/2016 11:31:44 PMtime="2016-08-17T21:31:44Z" level=info msg="Preparing server https &{Network: Address::8443 TLS:0xc820307680 Redirect:<nil>}" 
8/17/2016 11:31:44 PMtime="2016-08-17T21:31:44Z" level=info msg="Generating ACME Account..." 
8/17/2016 11:31:44 PMtime="2016-08-17T21:31:44Z" level=info msg="Starting server on :8080" 
8/17/2016 11:31:44 PMReinitializing monit daemon
8/17/2016 11:31:44 PMAwakened by the SIGHUP signal
8/17/2016 11:31:44 PMReinitializing Monit - Control file '/opt/monit/etc/monitrc'
8/17/2016 11:31:44 PM'traefik_traefik_1' Monit reloaded
8/17/2016 11:31:50 PMtime="2016-08-17T21:31:50Z" level=info msg="Starting provider *provider.File {\"Watch\":true,\"Filename\":\"/opt/traefik/etc/rules.toml\",\"Constraints\":null}" 
8/17/2016 11:31:50 PMtime="2016-08-17T21:31:50Z" level=info msg="Starting provider *main.WebProvider {\"Address\":\":8000\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false}" 
8/17/2016 11:31:50 PMtime="2016-08-17T21:31:50Z" level=info msg="Starting server on :8443" 
8/17/2016 11:31:50 PMtime="2016-08-17T21:31:50Z" level=info msg="Retrieving ACME certificates..." 
8/17/2016 11:31:50 PMtime="2016-08-17T21:31:50Z" level=info msg="Retrieved ACME certificates" 
8/17/2016 11:31:50 PMtime="2016-08-17T21:31:50Z" level=info msg="Server configuration reloaded on :8080" 
8/17/2016 11:31:50 PMtime="2016-08-17T21:31:50Z" level=info msg="Server configuration reloaded on :8443"

Thanks, best regards....

**Comment by fabiorauber** [comment]
@rawmind0 First, thanks for accepting the PR =D

I've tried the new release, and it works as long as the volume folder already exists on the host with the correct UID:GID set. In my setup, as I already had the folder present, owned by UID/GID 10001, it worked OK. So I tried to delete the folder, simulating someone first instantiating the service. Unfortunately, the folder was created owned by root, since it does not exist in rancher-traefik image. If the folder exists in the mentioned image, and is owned by traefik user, then the folder in the host is created with 10001 UID/GID, that's why I used the /opt/tools directory.

Here's a snippet of my docker-compose:

`traefik:
 ...
  image: rawmind/alpine-traefik:1.0.2-2
  volumes_from:
    - traefik-conf

traefik-conf:
  image: rawmind/rancher-traefik:0.3.4-4
  volumes:
    - /opt/tools
    - /var/cache/acme:/opt/traefik/acme
`

**Comment by rawmind0** [comment]
@fabiorauber thanks to you to collaborate... :)

Thanks to paste your docker-compose...Finally i've get what is the problem....

Try adding this acme-volume sidekick... ;P

```
traefik:
  image: rawmind/alpine-traefik:1.0.2-2
  volumes_from:
    - traefik-conf
    - acme-volume
traefik-conf:
  image: rawmind/rancher-traefik:0.3.4-4
  volumes:
    - /opt/tools
acme-volume:
  environment:
    - SERVICE_USER=traefik
    - SERVICE_UID= 10001
    - SERVICE_GROUP=traefik 
    - SERVICE_GID= 10001
    - SERVICE_VOLUME=/opt/traefik/acme
  volumes:
    - /var/cache/acme:/opt/traefik/acme
  image: rawmind/alpine-volume:0.0.1-1
```

Best regards....

**Comment by fabiorauber** [comment]
@rawmind0, thank you very much! Now it works fine. Still learning about docker volumes... =)

**Comment by rawmind0** [comment]
I updated alpine-volume image adding keep alive option to be run in k8s as well..
I made some change in the code to simplify.... :)

```
acme-volume:
  environment:
    - SERVICE_UID= 10001
    - SERVICE_GID= 10001
    - SERVICE_VOLUME=/opt/traefik/acme
  volumes:
    - /var/cache/acme:/opt/traefik/acme
  image: rawmind/alpine-volume:0.0.2-1
```

Best regards.....

**Pull request merged**
