### PR TITLE
WIP: Add support for wildcard certificate generation via ENV vars

### PR DESCRIPTION
**Pull request by krumware**
Adds env var `TRAEFIK_ACME_WILDCARD_DOMAINS`.

This method does not currently support multiple sans entries for a single domain.

### CODE REVIEW

**Comment by krumware** [comment]
Needed to wait for fixes included in today's Traefik release before resuming. Wildcards for nested domains were breaking the certificate requests in the adapter for our specific provider (namecheap). Will resume once the base master is updated.

**Comment by rawmind0** [comment]
@krumware , PR https://github.com/rawmind0/alpine-traefik/pull/130 already merged.

**Comment by krumware** [comment]
Thanks @rawmind0!
On initial tests, my certs are not being requested upon startup on the new branch. I need to verify functionality on my end before continuing. It may be that the bugfix for the namecheap adapter fixed one thing but exposed another. Anyways, doing due diligence

**Comment by krumware** [comment]
Good this time around, must have been environmental. Will get back to updating docs.

**Pull request closed without merging**
