### PR TITLE
Configure TLS on web backend

### PR DESCRIPTION
**Pull request by guylabs**
As there are always default TLS certificates generated we can
use them to secure the web backend by default.

### CODE REVIEW

**Comment by rawmind0** [comment]
Hi @guylabs, thanks so much for the PR.  :)

I like to add this option, but what do you think to control it by an env variable, like `TRAEFIK_ADMIN_SSL=true` ??

**Comment by guylabs** [comment]
Hi @rawmind0 

No problem. Thanks for maintaining the project ;). 

Yes we could add this. Shall I update the PR with this environment variable?

Thanks and regards

Guy

**Comment by rawmind0** [comment]
Yes please, if you could add env variable and i'll merge it asap. :)

**Comment by guylabs** [comment]
done.

**Comment by rawmind0** [comment]
Cool, thanks.... :)

LGTM...

**Comment by rawmind0** [comment]
Included at release rawmind/alpine-traefik:1.4.5-2

**Pull request merged**
