### PR TITLE
LetsEncrypt certificates and commercial ones should/can go side-by-side

### PR DESCRIPTION
**Pull request by adepretis**
Is there a reason that LE and commercial certificates are mutually exclusive? - if not, this PR allows both.

### CODE REVIEW

**Comment by adepretis** [comment]
any comments @rawmind0 ?

**Comment by rawmind0** [comment]
Thanks for the PR @adepretis.. Sorry about the delay, i could review it during this week...

**Comment by adepretis** [comment]
ping @rawmind0 ;-)

**Comment by rawmind0** [comment]
Sorry about the delay... LGTM

**Comment by rawmind0** [comment]
PR included at released image rawmind/alpine-traefik:1.7.3-1

**Pull request merged**
